name: build and publish docfx site
on: [push]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docfx-action
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docfx_project/docfx.json
      - name: Deploy to GitHub Pages with Container
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: docfx_project/_site
          GH_PAT: ${{ secrets.GH_PAT }}
